Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
busmap_kmeans = n.cluster.busmap_by_kmeans(bus_weightings=weighting, n_clusters=90)
------------------


[31m---------------------------------------------------------------------------[39m
[31mModuleNotFoundError[39m                       Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[7][39m[32m, line 1[39m
[32m----> [39m[32m1[39m busmap_kmeans = [43mn[49m[43m.[49m[43mcluster[49m[43m.[49m[43mbusmap_by_kmeans[49m[43m([49m[43mbus_weightings[49m[43m=[49m[43mweighting[49m[43m,[49m[43m [49m[43mn_clusters[49m[43m=[49m[32;43m90[39;49m[43m)[49m

[36mFile [39m[32m/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pypsa/clustering/__init__.py:34[39m, in [36mClusteringAccessor.busmap_by_kmeans[39m[34m(self, *args, **kwargs)[39m
[32m     32[39m [38;5;129m@wraps[39m(spatial.busmap_by_kmeans)
[32m     33[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34mbusmap_by_kmeans[39m([38;5;28mself[39m, *args: Any, **kwargs: Any) -> pd.Series:
[32m---> [39m[32m34[39m     [38;5;28;01mreturn[39;00m [43mspatial[49m[43m.[49m[43mbusmap_by_kmeans[49m[43m([49m[38;5;28;43mself[39;49m[43m.[49m[43mn[49m[43m,[49m[43m [49m[43m*[49m[43margs[49m[43m,[49m[43m [49m[43m*[49m[43m*[49m[43mkwargs[49m[43m)[49m

[36mFile [39m[32m/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pypsa/clustering/spatial.py:633[39m, in [36mbusmap_by_kmeans[39m[34m(n, bus_weightings, n_clusters, buses_i, **kwargs)[39m
[32m    610[39m [38;5;250m[39m[33;03m"""[39;00m
[32m    611[39m [33;03mCreate a bus map from the clustering of buses in space with a weighting.[39;00m
[32m    612[39m 
[32m   (...)[39m[32m    630[39m [33;03m    non-negative integers).[39;00m
[32m    631[39m [33;03m"""[39;00m
[32m    632[39m [38;5;28;01mif[39;00m find_spec([33m"[39m[33msklearn[39m[33m"[39m) [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[32m--> [39m[32m633[39m     [38;5;28;01mraise[39;00m [38;5;167;01mModuleNotFoundError[39;00m(
[32m    634[39m         [33m"[39m[33mOptional dependency [39m[33m'[39m[33msklearn[39m[33m'[39m[33m not found.[39m[33m"[39m
[32m    635[39m         [33m"[39m[33mInstall via [39m[33m'[39m[33mconda install -c conda-forge scikit-learn[39m[33m'[39m[33m [39m[33m"[39m
[32m    636[39m         [33m"[39m[33mor [39m[33m'[39m[33mpip install scikit-learn[39m[33m'[39m[33m"[39m
[32m    637[39m     )
[32m    639[39m [38;5;28;01mfrom[39;00m[38;5;250m [39m[34;01msklearn[39;00m[34;01m.[39;00m[34;01mcluster[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m KMeans
[32m    641[39m [38;5;28;01mif[39;00m buses_i [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:

[31mModuleNotFoundError[39m: Optional dependency 'sklearn' not found.Install via 'conda install -c conda-forge scikit-learn' or 'pip install scikit-learn'

